### ISSUE TITLE
[abandoned] problem when laying spike strips

### ISSUE THREAD

**Issue by Raph67110** [alexguirre/Spike-Strips-V#1]
Hello,

 first of all thank you for putting this code, it is really useful!
However, I had a few issues involved:

The first: by placing a harrow on the ground, the plugin crashes. I fixed the problem by removing the `Prop.SetRotationYaw (rotYaw);` and `HandleAnimations ();` in the stinger.cs file

Then, in game, when I put down a harrow, the animation runs endlessly and the harrow is levitated (at the player's height). 
The script works about once in 5 (animation of the harrow that is deploys)
attached some photos
https://imgur.com/vf5Ul1F
https://imgur.com/9s8ueoR
Thank you in advance for your help :)

P.S sorry for my bad English, I'm french ;)

**Comment by alexguirre** [comment]
Does it crash all the time? I used this script not too long ago and it surely did not crash each time I deployed a spike strip.

If those lines crash is because `Prop = new Object(Model, position);` returns an invalid handle, but it really shouldn't.

**Comment by Raph67110** [comment]
Yes, I reloaded game multiple Times ans I have the same problem. I will post my RagePluginHook log console asap
Thanks for tout Quick reply

**Comment by Raph67110** [comment]
I also have the problem with the compiled version on LCPDFR.com

**Comment by Raph67110** [comment]
There is the error
![bug3](https://user-images.githubusercontent.com/58261490/91660412-f9512600-ead5-11ea-9285-01e16defa43f.PNG)

**Comment by alexguirre** [comment]
And does it crash everywhere? Like it doesn't matter if you are in the city or the countryside, it always crashes?

**Comment by Raph67110** [comment]
Yes

**Comment by Raph67110** [comment]
I can't make it work
